name: Update Tidbyt Routine

on:
  # Run every 5 minutes (you can change to "*/1 * * * *" for every minute)
  schedule:
    - cron: "*/2 * * * *"
  # Allow manual runs from the GitHub UI
  workflow_dispatch:

jobs:
  push-routine:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install pixlet
        run: |
          curl -L -o pixlet.tar.gz \
            https://github.com/tidbyt/pixlet/releases/download/v0.34.0/pixlet_0.34.0_linux_amd64.tar.gz
          tar -xzf pixlet.tar.gz
          sudo mv pixlet /usr/local/bin/
          pixlet version

      - name: Render routine app
        run: |
          pixlet render routine.star

      - name: Push to Tidbyt
        run: |
          pixlet push \
            --api-token "${{ secrets.TIDBYT_API_TOKEN }}" \
            --installation-id routine \
            --device-id "${{ secrets.TIDBYT_DEVICE_ID }}" \
            routine.webp
